server:
  port:{$PORT:8080}

spring:
  application:
    name: brewlog
  datasource:
    url: jdbc:postgresql://postgresql://postgresql://brewlog_user:uo1vi0PYkuGrNd2fULbiErHez4urPmJ6@dpg-d9rkr7qfngtc73dk8r50-a.virginia-postgres.render.com/brewlog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # Optional: Explicit fallback if PostgreSQL driver metadata fails to load
        dialect: org.hibernate.dialect.PostgreSQLDialect
